/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/forecast-performance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Forecast Performance
         * @description 指定期間の保存済み事前予想について、展開ラベル的中率を返す。
         */
        get: operations["get_forecast_performance_api_v1_forecast_performance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ingest Status
         * @description 直近の取り込みバッチの鮮度・失敗有無を返す（トップ画面の更新状況表示用）。
         */
        get: operations["get_ingest_status_api_v1_ingest_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/races": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Races
         * @description 新しい順にレース一覧を返す。date 指定時はその日のレースのみ返す。
         */
        get: operations["list_races_api_v1_races_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/races/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Race Board
         * @description 指定日の一覧情報と軽量な展開予想を一括で返す。
         */
        get: operations["list_race_board_api_v1_races_board_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/races/dates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Race Dates
         * @description 全開催日を昇順で返す（カレンダー表示用）。
         */
        get: operations["list_race_dates_api_v1_races_dates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/races/{race_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Race Detail
         * @description レースの基本情報・出走馬・確定指標を返す。
         */
        get: operations["get_race_detail_api_v1_races__race_key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/races/{race_key}/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Race Forecast
         * @description 未確定レースの展開予想（想定RPCI・展開シナリオ・各馬 PAI）を返す。
         */
        get: operations["get_race_forecast_api_v1_races__race_key__forecast_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/races/{race_key}/pace-analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Race Pace Analysis
         * @description 確定後レースの各馬PCI・実績RPCI・PCI3（formula_version 付き）を返す。
         */
        get: operations["get_race_pace_analysis_api_v1_races__race_key__pace_analysis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/ingest/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Entries
         * @description 出走表登録（RegisterRaceEntriesUseCase を呼び出す）。
         */
        post: operations["ingest_entries_internal_ingest_entries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/ingest/forecasts/precompute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Precompute Forecasts
         * @description 今後の出走前レースの予想martを、画面表示より先に生成する。
         */
        post: operations["precompute_forecasts_internal_ingest_forecasts_precompute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/ingest/horses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Horses
         * @description 馬マスタ一括 Upsert。
         */
        post: operations["ingest_horses_internal_ingest_horses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/ingest/incomplete-race-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Incomplete Race Keys
         * @description 再同期対象となる成績未取り込みのJRA平地レースキーを全件返す。
         */
        get: operations["get_incomplete_race_keys_internal_ingest_incomplete_race_keys_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/ingest/jockeys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Jockeys
         * @description 騎手マスタ一括 Upsert。
         */
        post: operations["ingest_jockeys_internal_ingest_jockeys_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/ingest/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Write Ingest Log
         * @description バッチ取り込みの実行ログを記録する（監査証跡・再実行判定用）。
         */
        post: operations["write_ingest_log_internal_ingest_log_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/ingest/race-metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Race Metadata
         * @description 既存レースへ馬場状態・天候を上書きし、成績や出走馬は変更しない。
         */
        post: operations["ingest_race_metadata_internal_ingest_race_metadata_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/ingest/races/{race_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Ingested Race
         * @description 取り込み対象外になったレースを、関連する予想データごと削除する。
         */
        delete: operations["delete_ingested_race_internal_ingest_races__race_key__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/ingest/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Results
         * @description 確定成績登録（RecordRaceResultUseCase を呼び出す）。
         */
        post: operations["ingest_results_internal_ingest_results_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/ingest/trainers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Trainers
         * @description 調教師マスタ一括 Upsert。
         */
        post: operations["ingest_trainers_internal_ingest_trainers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description DB接続とマイグレーション適用状態を含む利用可能性を返す。
         */
        get: operations["readiness_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CommentSchema
         * @description 展開コメント（自然文の解説）。生成器の model_version を付す。
         */
        CommentSchema: {
            /**
             * Body
             * @default []
             */
            body: string[];
            /** Headline */
            headline: string;
            /** Model Version */
            model_version: string;
            /**
             * Reasons
             * @default []
             */
            reasons: components["schemas"]["ReasonSchema"][];
        };
        /** EntriesBody */
        EntriesBody: {
            /** Distance M */
            distance_m: number;
            /** Entries */
            entries: components["schemas"]["EntryItem"][];
            /** Field Size */
            field_size: number;
            /** Grade */
            grade?: string | null;
            /** Jyo Cd */
            jyo_cd: string;
            /** Race Class */
            race_class?: string | null;
            /**
             * Race Date
             * Format: date
             */
            race_date: string;
            /** Race Key */
            race_key: string;
            /** Track Condition */
            track_condition?: string | null;
            /** Track Type */
            track_type: string;
            /** Weather */
            weather?: string | null;
        };
        /**
         * EntryDetailSchema
         * @description 出走馬の詳細（確定済みなら成績を含む）。
         */
        EntryDetailSchema: {
            /** Finish Pos */
            finish_pos?: number | null;
            /** Frame No */
            frame_no: number;
            /** Horse No */
            horse_no: number;
            /** Ketto Num */
            ketto_num: string;
            /** Pci Actual */
            pci_actual?: number | null;
            /** Running Style */
            running_style?: string | null;
        };
        /** EntryItem */
        EntryItem: {
            /** Frame No */
            frame_no: number;
            /** Horse No */
            horse_no: number;
            /** Jockey Code */
            jockey_code: string;
            /** Ketto Num */
            ketto_num: string;
            /** Trainer Code */
            trainer_code: string;
            /** Weight */
            weight: number;
        };
        /**
         * ForecastAccuracySchema
         * @description 出走前の想定RPCIと実績RPCIの答え合わせ結果。
         */
        ForecastAccuracySchema: {
            /** Actual Label */
            actual_label: string;
            /** Actual Rpci */
            actual_rpci: number;
            /** Error */
            error: number;
            /** Label Hit */
            label_hit: boolean;
            /** Model Version */
            model_version: string;
            /** Predicted Label */
            predicted_label: string;
            /** Predicted Rpci */
            predicted_rpci: number;
        };
        /**
         * ForecastPaceMatrixCellSchema
         * @description 予想展開に対する実績展開1区分の件数と割合。
         */
        ForecastPaceMatrixCellSchema: {
            /** Count */
            count: number;
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Rate */
            rate?: number | null;
        };
        /**
         * ForecastPaceMatrixRowSchema
         * @description 予想展開1区分の実績分布。
         */
        ForecastPaceMatrixRowSchema: {
            /**
             * Cells
             * @default []
             */
            cells: components["schemas"]["ForecastPaceMatrixCellSchema"][];
            /** Predicted Key */
            predicted_key: string;
            /** Predicted Label */
            predicted_label: string;
            /** Sample Size */
            sample_size: number;
        };
        /**
         * ForecastPerformanceComparisonSchema
         * @description 直前の同期間における展開ラベル的中率。
         */
        ForecastPerformanceComparisonSchema: {
            /** Date From */
            date_from: string;
            /** Date To */
            date_to: string;
            /**
             * Groups
             * @default []
             */
            groups: components["schemas"]["ForecastPerformanceGroupSchema"][];
        };
        /**
         * ForecastPerformanceGroupSchema
         * @description コース種別ごとの展開ラベル的中率。
         */
        ForecastPerformanceGroupSchema: {
            /** Hit Count */
            hit_count: number;
            /** Hit Rate */
            hit_rate?: number | null;
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Sample Size */
            sample_size: number;
        };
        /**
         * ForecastPerformancePeriod
         * @description 画面で選択できる予想検証期間。
         * @enum {integer}
         */
        ForecastPerformancePeriod: 30 | 90 | 180;
        /**
         * ForecastPerformanceSchema
         * @description 直近期間の予想精度サマリー。PCI/RPCI実数値は公開しない。
         */
        ForecastPerformanceSchema: {
            /**
             * Confidence Groups
             * @default []
             */
            confidence_groups: components["schemas"]["ForecastPerformanceGroupSchema"][];
            /** Coverage Rate */
            coverage_rate?: number | null;
            /** Date From */
            date_from: string;
            /** Date To */
            date_to: string;
            /** Eligible Race Count */
            eligible_race_count: number;
            /**
             * Groups
             * @default []
             */
            groups: components["schemas"]["ForecastPerformanceGroupSchema"][];
            /** Hit Count */
            hit_count: number;
            /** Hit Rate */
            hit_rate?: number | null;
            /**
             * Pace Matrix
             * @default []
             */
            pace_matrix: components["schemas"]["ForecastPaceMatrixRowSchema"][];
            /** Period Days */
            period_days: number;
            previous_period: components["schemas"]["ForecastPerformanceComparisonSchema"];
            /** Sample Size */
            sample_size: number;
            /**
             * Weekly Trend
             * @default []
             */
            weekly_trend: components["schemas"]["ForecastPerformanceTrendPointSchema"][];
        };
        /**
         * ForecastPerformanceTrendPointSchema
         * @description 完了した1週間の展開ラベル的中率。
         */
        ForecastPerformanceTrendPointSchema: {
            /** Date From */
            date_from: string;
            /** Date To */
            date_to: string;
            /** Hit Count */
            hit_count: number;
            /** Hit Rate */
            hit_rate?: number | null;
            /** Sample Size */
            sample_size: number;
        };
        /** ForecastPrecomputeBody */
        ForecastPrecomputeBody: {
            /**
             * Date From
             * Format: date
             */
            date_from: string;
            /**
             * Date To
             * Format: date
             */
            date_to: string;
        };
        /** ForecastPrecomputeResponse */
        ForecastPrecomputeResponse: {
            /** Generated */
            generated: number;
            /** Scanned */
            scanned: number;
            /** Skipped */
            skipped: number;
        };
        /**
         * ForecastSchema
         * @description レース展開予想（想定RPCI + 展開シナリオ + 各馬 PAI）。
         */
        ForecastSchema: {
            /**
             * Beneficiaries
             * @default []
             */
            beneficiaries: number[];
            comment?: components["schemas"]["CommentSchema"] | null;
            /** Confidence */
            confidence: number;
            /**
             * Forecast Reasons
             * @default []
             */
            forecast_reasons: components["schemas"]["ReasonSchema"][];
            formation?: components["schemas"]["FormationSchema"] | null;
            /**
             * Front Runners
             * @default []
             */
            front_runners: number[];
            /**
             * Horses
             * @default []
             */
            horses: components["schemas"]["HorseFitSchema"][];
            integrated_ranking?: components["schemas"]["IntegratedRankingSchema"] | null;
            /** Model Version */
            model_version: string;
            /** Pace Label */
            pace_label: string;
            /** Predicted Rpci */
            predicted_rpci: number;
            /** Race Key */
            race_key: string;
            /** Scenario Detail */
            scenario_detail: string;
            /** Scenario Headline */
            scenario_headline: string;
            style_advantage?: components["schemas"]["StyleAdvantageSchema"] | null;
        };
        /**
         * FormationGroupSchema
         * @description 先頭・好位・中団・後方の隊列グループ。
         */
        FormationGroupSchema: {
            /**
             * Horses
             * @default []
             */
            horses: components["schemas"]["FormationHorseSchema"][];
            /** Key */
            key: string;
            /** Label */
            label: string;
        };
        /**
         * FormationHorseSchema
         * @description 隊列予想に表示する1頭分の配置。
         */
        FormationHorseSchema: {
            /** Confidence Label */
            confidence_label: string;
            /** Frame No */
            frame_no: number;
            /** Horse Name */
            horse_name?: string | null;
            /** Horse No */
            horse_no: number;
            /**
             * Reasons
             * @default []
             */
            reasons: components["schemas"]["ReasonSchema"][];
            /** Running Style */
            running_style: string;
        };
        /**
         * FormationSchema
         * @description 枠順確定後にのみ返す序盤隊列予想。
         */
        FormationSchema: {
            /**
             * Groups
             * @default []
             */
            groups: components["schemas"]["FormationGroupSchema"][];
            /** Model Version */
            model_version: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthSchema */
        HealthSchema: {
            /**
             * Status
             * @default ok
             */
            status: string;
        };
        /** HorseBody */
        HorseBody: {
            /** Birth Year */
            birth_year?: number | null;
            /** Ketto Num */
            ketto_num: string;
            /** Name */
            name: string;
            /** Sex */
            sex?: string | null;
        };
        /**
         * HorseFitSchema
         * @description 馬単位の展開適性（PAI）。
         *
         *     frame_no=0 は枠順未確定（特別登録段階）。horse_no はその場合、
         *     確定した公式馬番ではない可能性がある（FormationHorseSchema と同じ判定基準）。
         */
        HorseFitSchema: {
            /** Fit Label */
            fit_label: string;
            /** Frame No */
            frame_no: number;
            /** Horse Name */
            horse_name?: string | null;
            /** Horse No */
            horse_no: number;
            /** Pai */
            pai: number;
            /**
             * Reasons
             * @default []
             */
            reasons: components["schemas"]["ReasonSchema"][];
            /** Running Style */
            running_style: string;
        };
        /**
         * HorsePaceAnalysisSchema
         * @description 確定後の馬単位ペース分析（各馬 PCI）。
         */
        HorsePaceAnalysisSchema: {
            /** Agari 3F S */
            agari_3f_s?: number | null;
            /** Finish Pos */
            finish_pos?: number | null;
            /** Horse Name */
            horse_name?: string | null;
            /** Horse No */
            horse_no: number;
            /**
             * Is Pci3 Contributor
             * @default false
             */
            is_pci3_contributor: boolean;
            /** Pci */
            pci?: number | null;
            /** Running Style */
            running_style?: string | null;
        };
        /**
         * IncompleteRaceSchema
         * @description 開催日を過ぎても結果が反映されていないレース。
         */
        IncompleteRaceSchema: {
            /** Distance M */
            distance_m: number;
            /** Jyo Cd */
            jyo_cd: string;
            /** Race Date */
            race_date: string;
            /** Race Key */
            race_key: string;
            /** Track Type */
            track_type: string;
        };
        /**
         * IngestFailureSchema
         * @description 直近の取り込み失敗1件。
         */
        IngestFailureSchema: {
            /** Batch Date */
            batch_date: string;
            /** Error Summary */
            error_summary: string;
            /** Mode */
            mode: string;
            /** Started At */
            started_at: string;
            /** Step */
            step: string;
        };
        /**
         * IngestLogBody
         * @description バッチ実行ログの記録リクエスト。
         */
        IngestLogBody: {
            /**
             * Batch Date
             * Format: date
             */
            batch_date: string;
            /** Error Msg */
            error_msg?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Mode */
            mode: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Status */
            status?: string | null;
            /** Step */
            step: string;
        };
        /** IngestLogResponse */
        IngestLogResponse: {
            /** Id */
            id: number;
        };
        /** IngestResponse */
        IngestResponse: {
            /** Accepted */
            accepted: number;
            /**
             * Message
             * @default ok
             */
            message: string;
        };
        /**
         * IngestStatusSchema
         * @description 取り込みバッチの鮮度サマリ（トップ画面の更新状況表示に使用）。
         *
         *     has_history=False は「ログが無い（開発/fixture環境等）」を表し、異常を意味しない。
         */
        IngestStatusSchema: {
            /** Days Since Last Success */
            days_since_last_success?: number | null;
            /** Has History */
            has_history: boolean;
            /**
             * Has Incomplete Races
             * @default false
             */
            has_incomplete_races: boolean;
            /**
             * Has Missing Track Conditions
             * @default false
             */
            has_missing_track_conditions: boolean;
            /**
             * Incomplete Race Count
             * @default 0
             */
            incomplete_race_count: number;
            /**
             * Incomplete Races
             * @default []
             */
            incomplete_races: components["schemas"]["IncompleteRaceSchema"][];
            /**
             * Is Stale
             * @default false
             */
            is_stale: boolean;
            /**
             * Last Attempt Failed
             * @default false
             */
            last_attempt_failed: boolean;
            /** Last Success At */
            last_success_at?: string | null;
            /** Last Success Step */
            last_success_step?: string | null;
            /**
             * Missing Track Condition Count
             * @default 0
             */
            missing_track_condition_count: number;
            /**
             * Missing Track Condition Races
             * @default []
             */
            missing_track_condition_races: components["schemas"]["MissingTrackConditionRaceSchema"][];
            /** Race Metadata Date From */
            race_metadata_date_from: string;
            /** Race Metadata Date To */
            race_metadata_date_to: string;
            /**
             * Recent Failures
             * @default []
             */
            recent_failures: components["schemas"]["IngestFailureSchema"][];
            /** Recommended Sync Days Back */
            recommended_sync_days_back: number;
        };
        /**
         * IntegratedEntrySchema
         * @description 統合順位予想の1頭分（展開×能力の2軸分類）。
         *
         *     frame_no=0 は枠順未確定（HorseFitSchema と同じ判定基準）。
         */
        IntegratedEntrySchema: {
            /** Ability Tier */
            ability_tier: string;
            /** Fit Label */
            fit_label: string;
            /** Frame No */
            frame_no: number;
            /** Horse Name */
            horse_name?: string | null;
            /** Horse No */
            horse_no: number;
            /** Mark */
            mark: string;
            /** Rank */
            rank: number;
            /**
             * Reasons
             * @default []
             */
            reasons: components["schemas"]["ReasonSchema"][];
        };
        /**
         * IntegratedRankingSchema
         * @description 展開適性と能力の2軸統合順位予想（integrated-v1）。
         */
        IntegratedRankingSchema: {
            /**
             * Entries
             * @default []
             */
            entries: components["schemas"]["IntegratedEntrySchema"][];
            /** Model Version */
            model_version: string;
            /**
             * Reasons
             * @default []
             */
            reasons: components["schemas"]["ReasonSchema"][];
        };
        /** JockeyBody */
        JockeyBody: {
            /** Code */
            code: string;
            /** Name */
            name: string;
        };
        /**
         * MissingTrackConditionRaceSchema
         * @description 確定済みだが馬場状態が反映されていないレース。
         */
        MissingTrackConditionRaceSchema: {
            /** Distance M */
            distance_m: number;
            /** Jyo Cd */
            jyo_cd: string;
            /** Race Date */
            race_date: string;
            /** Race Key */
            race_key: string;
            /** Track Type */
            track_type: string;
        };
        /**
         * PaceAnalysisSchema
         * @description 確定後ペース分析（各馬PCI・実績RPCI・PCI3）。PCI 系は formula_version を返す。
         */
        PaceAnalysisSchema: {
            comment?: components["schemas"]["CommentSchema"] | null;
            /** Field Size */
            field_size: number;
            forecast_accuracy?: components["schemas"]["ForecastAccuracySchema"] | null;
            /** Formula Version */
            formula_version: string;
            /**
             * Horses
             * @default []
             */
            horses: components["schemas"]["HorsePaceAnalysisSchema"][];
            /** Pci3 Actual */
            pci3_actual?: number | null;
            /** Race Key */
            race_key: string;
            /**
             * Reasons
             * @default []
             */
            reasons: components["schemas"]["ReasonSchema"][];
            /** Rpci Actual */
            rpci_actual?: number | null;
            /** Sample Size */
            sample_size: number;
        };
        /**
         * RaceBoardForecastSchema
         * @description 一覧用の軽量予想。PCI/RPCIの内部実数値は含めない。
         */
        RaceBoardForecastSchema: {
            /** Confidence */
            confidence: number;
            /** Pace Label */
            pace_label: string;
            /** Top Fit Label */
            top_fit_label: string;
            /** Top Fit Strength */
            top_fit_strength: string;
            /** Top Horse Name */
            top_horse_name?: string | null;
            /** Top Horse No */
            top_horse_no: number;
        };
        /**
         * RaceBoardItemSchema
         * @description レースボードの1件分。
         */
        RaceBoardItemSchema: {
            forecast?: components["schemas"]["RaceBoardForecastSchema"] | null;
            race: components["schemas"]["RaceSummarySchema"];
        };
        /**
         * RaceDetailSchema
         * @description レース詳細（core 層の情報 + 確定指標）。
         */
        RaceDetailSchema: {
            /** Distance M */
            distance_m: number;
            /**
             * Entries
             * @default []
             */
            entries: components["schemas"]["EntryDetailSchema"][];
            /** Field Size */
            field_size: number;
            /** Grade */
            grade?: string | null;
            /** Jyo Cd */
            jyo_cd: string;
            /** Pci3 Actual */
            pci3_actual?: number | null;
            /** Race Class */
            race_class?: string | null;
            /** Race Date */
            race_date: string;
            /** Race Key */
            race_key: string;
            /** Rpci Actual */
            rpci_actual?: number | null;
            /** Status */
            status: string;
            /** Track Condition */
            track_condition?: string | null;
            /** Track Type */
            track_type: string;
            /** Weather */
            weather?: string | null;
        };
        /** RaceMetadataBody */
        RaceMetadataBody: {
            /** Race Key */
            race_key: string;
            /** Track Condition */
            track_condition?: string | null;
            /** Weather */
            weather?: string | null;
        };
        /**
         * RaceSummarySchema
         * @description レース一覧の1件分（トップ画面のレース選択用）。
         *
         *     status で遷移先（entries=展開予想／result=ペース分析）を判別する。
         */
        RaceSummarySchema: {
            /** Distance M */
            distance_m: number;
            /** Field Size */
            field_size: number;
            /** Grade */
            grade?: string | null;
            /** Jyo Cd */
            jyo_cd: string;
            /** Race Class */
            race_class?: string | null;
            /** Race Date */
            race_date: string;
            /** Race Key */
            race_key: string;
            /** Status */
            status: string;
            /** Track Type */
            track_type: string;
        };
        /** ReadinessSchema */
        ReadinessSchema: {
            /** Action */
            action?: string | null;
            /**
             * Database
             * @enum {string}
             */
            database: "ok" | "unavailable" | "schema_outdated";
            /** Message */
            message?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "not_ready";
        };
        /**
         * ReasonSchema
         * @description 説明可能性の根拠（要因コード・説明・寄与度）。
         */
        ReasonSchema: {
            /** Code */
            code: string;
            /** Contribution */
            contribution?: number | null;
            /** Description */
            description: string;
        };
        /** ResultBody */
        ResultBody: {
            /** Grade */
            grade?: string | null;
            /** Race Key */
            race_key: string;
            /** Race L3F */
            race_l3f?: number | null;
            /** Race S3F */
            race_s3f?: number | null;
            /** Results */
            results: components["schemas"]["ResultItem"][];
            /** Track Condition */
            track_condition?: string | null;
            /** Weather */
            weather?: string | null;
        };
        /** ResultItem */
        ResultItem: {
            /** Agari 3F S */
            agari_3f_s: number;
            /** Body Weight */
            body_weight?: number | null;
            /** Corner 1 */
            corner_1?: number | null;
            /** Corner 2 */
            corner_2?: number | null;
            /** Corner 3 */
            corner_3?: number | null;
            /** Corner 4 */
            corner_4?: number | null;
            /** Finish Pos */
            finish_pos: number;
            /** Horse No */
            horse_no: number;
            /** Popularity */
            popularity?: number | null;
            /** Prize Money */
            prize_money?: number | null;
            /** Race Time S */
            race_time_s: number;
        };
        /** ResultResponse */
        ResultResponse: {
            /**
             * Entry Pcis
             * @default {}
             */
            entry_pcis: {
                [key: string]: number;
            };
            /** Formula Version */
            formula_version: string;
            /** Pci3 */
            pci3: number | null;
            /** Race Key */
            race_key: string;
            /** Rpci */
            rpci: number | null;
        };
        /**
         * StyleAdvantageEntrySchema
         * @description 1脚質分の展開有利度（50=互角、大きいほど今回の流れが向く）。
         */
        StyleAdvantageEntrySchema: {
            /** Score */
            score: number;
            /** Style */
            style: string;
        };
        /**
         * StyleAdvantageSchema
         * @description 脚質別の展開有利度（style-advantage-v3）。
         */
        StyleAdvantageSchema: {
            /**
             * Entries
             * @default []
             */
            entries: components["schemas"]["StyleAdvantageEntrySchema"][];
            /** Model Version */
            model_version: string;
            /**
             * Reasons
             * @default []
             */
            reasons: components["schemas"]["ReasonSchema"][];
            /**
             * Reliability
             * @default standard
             * @enum {string}
             */
            reliability: "standard" | "reference";
            /** Reliability Reason */
            reliability_reason?: string | null;
        };
        /** TrainerBody */
        TrainerBody: {
            /** Code */
            code: string;
            /** Name */
            name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_forecast_performance_api_v1_forecast_performance_get: {
        parameters: {
            query?: {
                days?: components["schemas"]["ForecastPerformancePeriod"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastPerformanceSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ingest_status_api_v1_ingest_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestStatusSchema"];
                };
            };
        };
    };
    list_races_api_v1_races_get: {
        parameters: {
            query?: {
                /** @description 取得件数の上限 */
                limit?: number;
                /** @description 絞り込む開催日（YYYY-MM-DD） */
                date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RaceSummarySchema"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_race_board_api_v1_races_board_get: {
        parameters: {
            query: {
                /** @description 開催日（YYYY-MM-DD） */
                date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RaceBoardItemSchema"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_race_dates_api_v1_races_dates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    get_race_detail_api_v1_races__race_key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 16桁のレースキー */
                race_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RaceDetailSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_race_forecast_api_v1_races__race_key__forecast_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 16桁のレースキー */
                race_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_race_pace_analysis_api_v1_races__race_key__pace_analysis_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 16桁のレースキー */
                race_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaceAnalysisSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthSchema"];
                };
            };
        };
    };
    ingest_entries_internal_ingest_entries_post: {
        parameters: {
            query?: never;
            header?: {
                "x-ingest-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntriesBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    precompute_forecasts_internal_ingest_forecasts_precompute_post: {
        parameters: {
            query?: never;
            header?: {
                "x-ingest-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForecastPrecomputeBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastPrecomputeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_horses_internal_ingest_horses_post: {
        parameters: {
            query?: never;
            header?: {
                "x-ingest-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HorseBody"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_incomplete_race_keys_internal_ingest_incomplete_race_keys_get: {
        parameters: {
            query?: never;
            header?: {
                "x-ingest-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_jockeys_internal_ingest_jockeys_post: {
        parameters: {
            query?: never;
            header?: {
                "x-ingest-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JockeyBody"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    write_ingest_log_internal_ingest_log_post: {
        parameters: {
            query?: never;
            header?: {
                "x-ingest-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestLogBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestLogResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_race_metadata_internal_ingest_race_metadata_post: {
        parameters: {
            query?: never;
            header?: {
                "x-ingest-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RaceMetadataBody"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_ingested_race_internal_ingest_races__race_key__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-ingest-token"?: string | null;
            };
            path: {
                race_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_results_internal_ingest_results_post: {
        parameters: {
            query?: never;
            header?: {
                "x-ingest-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResultBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_trainers_internal_ingest_trainers_post: {
        parameters: {
            query?: never;
            header?: {
                "x-ingest-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrainerBody"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readiness_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessSchema"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessSchema"];
                };
            };
        };
    };
}
