/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/races/{race_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Race Detail
         * @description レースの基本情報・出走馬・確定指標を返す。
         */
        get: operations["get_race_detail_api_v1_races__race_key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/races/{race_key}/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Race Forecast
         * @description 未確定レースの展開予想（想定RPCI・展開シナリオ・各馬 PAI）を返す。
         */
        get: operations["get_race_forecast_api_v1_races__race_key__forecast_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * EntryDetailSchema
         * @description 出走馬の詳細（確定済みなら成績を含む）。
         */
        EntryDetailSchema: {
            /** Finish Pos */
            finish_pos?: number | null;
            /** Frame No */
            frame_no: number;
            /** Horse No */
            horse_no: number;
            /** Ketto Num */
            ketto_num: string;
            /** Pci Actual */
            pci_actual?: number | null;
            /** Running Style */
            running_style?: string | null;
        };
        /**
         * ForecastSchema
         * @description レース展開予想（想定RPCI + 展開シナリオ + 各馬 PAI）。
         */
        ForecastSchema: {
            /**
             * Beneficiaries
             * @default []
             */
            beneficiaries: number[];
            /** Confidence */
            confidence: number;
            /**
             * Forecast Reasons
             * @default []
             */
            forecast_reasons: components["schemas"]["ReasonSchema"][];
            /**
             * Front Runners
             * @default []
             */
            front_runners: number[];
            /**
             * Horses
             * @default []
             */
            horses: components["schemas"]["HorseFitSchema"][];
            /** Model Version */
            model_version: string;
            /** Pace Label */
            pace_label: string;
            /** Predicted Rpci */
            predicted_rpci: number;
            /** Race Key */
            race_key: string;
            /** Scenario Detail */
            scenario_detail: string;
            /** Scenario Headline */
            scenario_headline: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthSchema */
        HealthSchema: {
            /**
             * Status
             * @default ok
             */
            status: string;
        };
        /**
         * HorseFitSchema
         * @description 馬単位の展開適性（PAI）。
         */
        HorseFitSchema: {
            /** Fit Label */
            fit_label: string;
            /** Horse No */
            horse_no: number;
            /** Pai */
            pai: number;
            /**
             * Reasons
             * @default []
             */
            reasons: components["schemas"]["ReasonSchema"][];
            /** Running Style */
            running_style: string;
        };
        /**
         * RaceDetailSchema
         * @description レース詳細（core 層の情報 + 確定指標）。
         */
        RaceDetailSchema: {
            /** Distance M */
            distance_m: number;
            /**
             * Entries
             * @default []
             */
            entries: components["schemas"]["EntryDetailSchema"][];
            /** Field Size */
            field_size: number;
            /** Grade */
            grade?: string | null;
            /** Jyo Cd */
            jyo_cd: string;
            /** Pci3 Actual */
            pci3_actual?: number | null;
            /** Race Class */
            race_class?: string | null;
            /** Race Date */
            race_date: string;
            /** Race Key */
            race_key: string;
            /** Rpci Actual */
            rpci_actual?: number | null;
            /** Status */
            status: string;
            /** Track Condition */
            track_condition?: string | null;
            /** Track Type */
            track_type: string;
            /** Weather */
            weather?: string | null;
        };
        /**
         * ReasonSchema
         * @description 説明可能性の根拠（要因コード・説明・寄与度）。
         */
        ReasonSchema: {
            /** Code */
            code: string;
            /** Contribution */
            contribution?: number | null;
            /** Description */
            description: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_race_detail_api_v1_races__race_key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 16桁のレースキー */
                race_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RaceDetailSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_race_forecast_api_v1_races__race_key__forecast_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 16桁のレースキー */
                race_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthSchema"];
                };
            };
        };
    };
}
